Repository CosmosContracts/juno-tools, pull requests merged in 2022-04, with the labels that each got.

#101 feat(pages): implement cw20 pages
  components/FormControl.tsx
  components/FormGroup.tsx
  components/Input.tsx
  components/LinkTab.tsx
  components/LinkTabs.data.ts
  components/LinkTabs.tsx
  components/PageHeader.tsx
  components/PageHeaderCW20.tsx
  components/Sidebar.tsx
  hooks/useInstantiateCW20Form.ts
  package.json
  pages/contracts/cw20/execute.tsx
  pages/contracts/cw20/index.tsx
  pages/contracts/cw20/instantiate.tsx
  pages/contracts/cw20/query.tsx
  utils/cw20.ts
  utils/links.ts
  yarn.lock
Labels: enhancement

#129 refactor(ctx): merge keplr wallet store
  components/WalletLoader.tsx
  config/keplr.ts
  contexts/contracts.tsx
  contexts/wallet.tsx
  env.d.ts
  package.json
  pages/_app.tsx
  services/keplr.ts
  yarn.lock
Labels: enhancement, dx

#126 refactor(ui): rework wallet loader component
  components/WalletButton.tsx
  components/WalletLoader.tsx
  components/WalletPanelButton.tsx
  package.json
  yarn.lock
Labels: enhancement, dx

#130 feat(ctx): add contracts and wallet ctx docs
  contexts/contracts.tsx
  contexts/wallet.tsx
Labels: enhancement, dx

#132 chore(ctx): remove sidebar persist
  contexts/sidebar.ts
Labels: enhancement

#133 chore(deps): bump versions
  yarn.lock
Labels: enhancement

#134 chore(env): update example and declarations
  .env.example
  env.d.ts
Labels: enhancement, dx

#136 chore(assets): move brand svgs to public directory
  components/BrandPreview.tsx
  components/Sidebar.tsx
  pages/brand.tsx
  pages/index.tsx
  public/brand/brand-bust.svg
  public/brand/brand-text.svg
  public/brand/brand.svg
Labels: enhancement

#135 fix(ui): remove useless wallet loader fragment
  components/WalletLoader.tsx
Labels: enhancement

#137 fix(ui): prefix twitter card image with website url
  components/DefaultAppSeo.tsx
  next.config.js
  package.json
  utils/constants.ts
Labels: enhancement, dx

#122 feat(pages): improve airdrop list page
  components/AirdropsTable.tsx
  pages/airdrops/list.tsx
  utils/airdrop.ts
  utils/text.ts
Labels: enhancement

#131 feat(pages): add address inputs for cw20 queries
  pages/contracts/cw20/query.tsx
  utils/cw20.ts
Labels: enhancement

#158 refactor(ui): change to named exports
  .vscode/settings.json
  components/AirdropStatus.tsx
  components/AirdropsStepper.tsx
  components/AirdropsTable.tsx
  components/Alert.tsx
  components/Anchor.tsx
  components/AnchorButton.tsx
  components/BrandColorPicker.tsx
  components/BrandPreview.tsx
  components/Button.tsx
  components/Conditional.tsx
  components/DefaultAppSeo.tsx
  components/FaviconsMetaTags.jsx
  components/FormControl.tsx
  components/FormGroup.tsx
  components/HomeCard.tsx
  components/Input.tsx
  components/InputDateTime.tsx
  components/Issuebar.tsx
  components/JsonPreview.tsx
  components/Layout.tsx
  components/LinkTab.tsx
  components/LinkTabs.tsx
  components/Modal.tsx
  components/PageHeader.tsx
  components/PageHeaderCW20.tsx
  components/Radio.tsx
  components/SearchInput.tsx
  components/Sidebar.tsx
  components/SidebarLayout.tsx
  components/StackedList.tsx
  components/Stats.tsx
  components/TextArea.tsx
  components/Tooltip.tsx
  components/TooltipIcon.tsx
  components/WalletButton.tsx
  components/WalletLoader.tsx
  components/WalletPanelButton.tsx
  contexts/contracts.tsx
  contexts/wallet.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/airdrops/[address]/claim.tsx
  pages/airdrops/create.tsx
  pages/airdrops/escrow.tsx
  pages/airdrops/fund.tsx
  pages/airdrops/list.tsx
  pages/airdrops/register.tsx
  pages/airdrops/success.tsx
  pages/brand.tsx
  pages/contracts/cw20/execute.tsx
  pages/contracts/cw20/instantiate.tsx
  pages/contracts/cw20/query.tsx
  pages/index.tsx
  pages/sign-verify.tsx
Labels: dx
